export interface Match {
  homeCode: string;
  homeName: string;
  homeFlag: string;
  awayCode: string;
  awayName: string;
  awayFlag: string;
  date: string;      // "YYYY-MM-DD" in BD time
  dateLabel: string; // "Jun 12"   in BD time
  time: string;      // "1:00 AM"  in BD time
  group: string;
  status: "upcoming" | "live" | "done";
}

/** Unique key per match used as the prediction identifier. */
export function matchKey(m: Match): string {
  return `${m.homeCode}_${m.awayCode}_${m.date}`;
}

/**
 * Static fallback list (group stage only, BD times).
 * Used only when the backend API is unreachable.
 * Live data comes from fetchAllFixtures() in fixtures.ts.
 */
const FLAG = (cc: string) => `https://flagcdn.com/w80/${cc}.png`;

export const allMatches: Match[] = [
  // Jun 12
  {
    homeCode: "MEX",
    homeName: "Mexico",
    homeFlag: FLAG("mx"),
    awayCode: "RSA",
    awayName: "South Africa",
    awayFlag: FLAG("za"),
    date: "2026-06-12",
    dateLabel: "Jun 12",
    time: "1:00 AM",
    group: "A",
    status: "upcoming",
  },
  {
    homeCode: "KOR",
    homeName: "Korea",
    homeFlag: FLAG("kr"),
    awayCode: "CZE",
    awayName: "Czechia",
    awayFlag: FLAG("cz"),
    date: "2026-06-12",
    dateLabel: "Jun 12",
    time: "8:00 AM",
    group: "A",
    status: "upcoming",
  },
  // Jun 13
  {
    homeCode: "CAN",
    homeName: "Canada",
    homeFlag: FLAG("ca"),
    awayCode: "BIH",
    awayName: "Bosnia",
    awayFlag: FLAG("ba"),
    date: "2026-06-13",
    dateLabel: "Jun 13",
    time: "1:00 AM",
    group: "B",
    status: "upcoming",
  },
  {
    homeCode: "USA",
    homeName: "USA",
    homeFlag: FLAG("us"),
    awayCode: "PAR",
    awayName: "Paraguay",
    awayFlag: FLAG("py"),
    date: "2026-06-13",
    dateLabel: "Jun 13",
    time: "7:00 AM",
    group: "D",
    status: "upcoming",
  },
  // Jun 14
  {
    homeCode: "QAT",
    homeName: "Qatar",
    homeFlag: FLAG("qa"),
    awayCode: "SUI",
    awayName: "Switzerland",
    awayFlag: FLAG("ch"),
    date: "2026-06-14",
    dateLabel: "Jun 14",
    time: "1:00 AM",
    group: "B",
    status: "upcoming",
  },
  {
    homeCode: "BRA",
    homeName: "Brazil",
    homeFlag: FLAG("br"),
    awayCode: "MAR",
    awayName: "Morocco",
    awayFlag: FLAG("ma"),
    date: "2026-06-14",
    dateLabel: "Jun 14",
    time: "4:00 AM",
    group: "C",
    status: "upcoming",
  },
  {
    homeCode: "HAI",
    homeName: "Haiti",
    homeFlag: FLAG("ht"),
    awayCode: "SCO",
    awayName: "Scotland",
    awayFlag: FLAG("gb-sct"),
    date: "2026-06-14",
    dateLabel: "Jun 14",
    time: "7:00 AM",
    group: "C",
    status: "upcoming",
  },
  {
    homeCode: "AUS",
    homeName: "Australia",
    homeFlag: FLAG("au"),
    awayCode: "TUR",
    awayName: "Turkey",
    awayFlag: FLAG("tr"),
    date: "2026-06-14",
    dateLabel: "Jun 14",
    time: "10:00 AM",
    group: "D",
    status: "upcoming",
  },
  {
    homeCode: "GER",
    homeName: "Germany",
    homeFlag: FLAG("de"),
    awayCode: "CUW",
    awayName: "Curaçao",
    awayFlag: FLAG("cw"),
    date: "2026-06-14",
    dateLabel: "Jun 14",
    time: "11:00 PM",
    group: "E",
    status: "upcoming",
  },
  // Jun 15
  {
    homeCode: "NED",
    homeName: "Netherlands",
    homeFlag: FLAG("nl"),
    awayCode: "JPN",
    awayName: "Japan",
    awayFlag: FLAG("jp"),
    date: "2026-06-15",
    dateLabel: "Jun 15",
    time: "2:00 AM",
    group: "F",
    status: "upcoming",
  },
  {
    homeCode: "CIV",
    homeName: "Côte d'Ivoire",
    homeFlag: FLAG("ci"),
    awayCode: "ECU",
    awayName: "Ecuador",
    awayFlag: FLAG("ec"),
    date: "2026-06-15",
    dateLabel: "Jun 15",
    time: "5:00 AM",
    group: "E",
    status: "upcoming",
  },
  {
    homeCode: "SWE",
    homeName: "Sweden",
    homeFlag: FLAG("se"),
    awayCode: "TUN",
    awayName: "Tunisia",
    awayFlag: FLAG("tn"),
    date: "2026-06-15",
    dateLabel: "Jun 15",
    time: "8:00 AM",
    group: "F",
    status: "upcoming",
  },
  {
    homeCode: "ESP",
    homeName: "Spain",
    homeFlag: FLAG("es"),
    awayCode: "CPV",
    awayName: "Cabo Verde",
    awayFlag: FLAG("cv"),
    date: "2026-06-15",
    dateLabel: "Jun 15",
    time: "10:00 PM",
    group: "H",
    status: "upcoming",
  },
  // Jun 16
  {
    homeCode: "BEL",
    homeName: "Belgium",
    homeFlag: FLAG("be"),
    awayCode: "EGY",
    awayName: "Egypt",
    awayFlag: FLAG("eg"),
    date: "2026-06-16",
    dateLabel: "Jun 16",
    time: "1:00 AM",
    group: "G",
    status: "upcoming",
  },
  {
    homeCode: "KSA",
    homeName: "Saudi Arabia",
    homeFlag: FLAG("sa"),
    awayCode: "URU",
    awayName: "Uruguay",
    awayFlag: FLAG("uy"),
    date: "2026-06-16",
    dateLabel: "Jun 16",
    time: "4:00 AM",
    group: "H",
    status: "upcoming",
  },
  {
    homeCode: "IRN",
    homeName: "Iran",
    homeFlag: FLAG("ir"),
    awayCode: "NZL",
    awayName: "New Zealand",
    awayFlag: FLAG("nz"),
    date: "2026-06-16",
    dateLabel: "Jun 16",
    time: "7:00 AM",
    group: "G",
    status: "upcoming",
  },
  // Jun 17
  {
    homeCode: "FRA",
    homeName: "France",
    homeFlag: FLAG("fr"),
    awayCode: "SEN",
    awayName: "Senegal",
    awayFlag: FLAG("sn"),
    date: "2026-06-17",
    dateLabel: "Jun 17",
    time: "1:00 AM",
    group: "I",
    status: "upcoming",
  },
  {
    homeCode: "IRQ",
    homeName: "Iraq",
    homeFlag: FLAG("iq"),
    awayCode: "NOR",
    awayName: "Norway",
    awayFlag: FLAG("no"),
    date: "2026-06-17",
    dateLabel: "Jun 17",
    time: "4:00 AM",
    group: "I",
    status: "upcoming",
  },
  {
    homeCode: "ARG",
    homeName: "Argentina",
    homeFlag: FLAG("ar"),
    awayCode: "ALG",
    awayName: "Algeria",
    awayFlag: FLAG("dz"),
    date: "2026-06-17",
    dateLabel: "Jun 17",
    time: "7:00 AM",
    group: "J",
    status: "upcoming",
  },
  {
    homeCode: "AUT",
    homeName: "Austria",
    homeFlag: FLAG("at"),
    awayCode: "JOR",
    awayName: "Jordan",
    awayFlag: FLAG("jo"),
    date: "2026-06-17",
    dateLabel: "Jun 17",
    time: "10:00 AM",
    group: "J",
    status: "upcoming",
  },
  {
    homeCode: "POR",
    homeName: "Portugal",
    homeFlag: FLAG("pt"),
    awayCode: "COD",
    awayName: "DR Congo",
    awayFlag: FLAG("cd"),
    date: "2026-06-17",
    dateLabel: "Jun 17",
    time: "11:00 PM",
    group: "K",
    status: "upcoming",
  },
  // Jun 18
  {
    homeCode: "ENG",
    homeName: "England",
    homeFlag: FLAG("gb-eng"),
    awayCode: "CRO",
    awayName: "Croatia",
    awayFlag: FLAG("hr"),
    date: "2026-06-18",
    dateLabel: "Jun 18",
    time: "2:00 AM",
    group: "L",
    status: "upcoming",
  },
  {
    homeCode: "GHA",
    homeName: "Ghana",
    homeFlag: FLAG("gh"),
    awayCode: "PAN",
    awayName: "Panama",
    awayFlag: FLAG("pa"),
    date: "2026-06-18",
    dateLabel: "Jun 18",
    time: "5:00 AM",
    group: "L",
    status: "upcoming",
  },
  {
    homeCode: "UZB",
    homeName: "Uzbekistan",
    homeFlag: FLAG("uz"),
    awayCode: "COL",
    awayName: "Colombia",
    awayFlag: FLAG("co"),
    date: "2026-06-18",
    dateLabel: "Jun 18",
    time: "8:00 AM",
    group: "K",
    status: "upcoming",
  },
  {
    homeCode: "CZE",
    homeName: "Czechia",
    homeFlag: FLAG("cz"),
    awayCode: "RSA",
    awayName: "South Africa",
    awayFlag: FLAG("za"),
    date: "2026-06-18",
    dateLabel: "Jun 18",
    time: "10:00 PM",
    group: "A",
    status: "upcoming",
  },
  // Jun 19
  {
    homeCode: "SUI",
    homeName: "Switzerland",
    homeFlag: FLAG("ch"),
    awayCode: "BIH",
    awayName: "Bosnia",
    awayFlag: FLAG("ba"),
    date: "2026-06-19",
    dateLabel: "Jun 19",
    time: "1:00 AM",
    group: "B",
    status: "upcoming",
  },
  {
    homeCode: "CAN",
    homeName: "Canada",
    homeFlag: FLAG("ca"),
    awayCode: "QAT",
    awayName: "Qatar",
    awayFlag: FLAG("qa"),
    date: "2026-06-19",
    dateLabel: "Jun 19",
    time: "4:00 AM",
    group: "B",
    status: "upcoming",
  },
  {
    homeCode: "MEX",
    homeName: "Mexico",
    homeFlag: FLAG("mx"),
    awayCode: "KOR",
    awayName: "Korea",
    awayFlag: FLAG("kr"),
    date: "2026-06-19",
    dateLabel: "Jun 19",
    time: "7:00 AM",
    group: "A",
    status: "upcoming",
  },
  // Jun 20
  {
    homeCode: "USA",
    homeName: "USA",
    homeFlag: FLAG("us"),
    awayCode: "AUS",
    awayName: "Australia",
    awayFlag: FLAG("au"),
    date: "2026-06-20",
    dateLabel: "Jun 20",
    time: "1:00 AM",
    group: "D",
    status: "upcoming",
  },
  {
    homeCode: "SCO",
    homeName: "Scotland",
    homeFlag: FLAG("gb-sct"),
    awayCode: "MAR",
    awayName: "Morocco",
    awayFlag: FLAG("ma"),
    date: "2026-06-20",
    dateLabel: "Jun 20",
    time: "4:00 AM",
    group: "C",
    status: "upcoming",
  },
  {
    homeCode: "BRA",
    homeName: "Brazil",
    homeFlag: FLAG("br"),
    awayCode: "HAI",
    awayName: "Haiti",
    awayFlag: FLAG("ht"),
    date: "2026-06-20",
    dateLabel: "Jun 20",
    time: "6:30 AM",
    group: "C",
    status: "upcoming",
  },
  {
    homeCode: "TUR",
    homeName: "Turkey",
    homeFlag: FLAG("tr"),
    awayCode: "PAR",
    awayName: "Paraguay",
    awayFlag: FLAG("py"),
    date: "2026-06-20",
    dateLabel: "Jun 20",
    time: "9:00 AM",
    group: "D",
    status: "upcoming",
  },
  {
    homeCode: "NED",
    homeName: "Netherlands",
    homeFlag: FLAG("nl"),
    awayCode: "SWE",
    awayName: "Sweden",
    awayFlag: FLAG("se"),
    date: "2026-06-20",
    dateLabel: "Jun 20",
    time: "11:00 PM",
    group: "F",
    status: "upcoming",
  },
  // Jun 21
  {
    homeCode: "GER",
    homeName: "Germany",
    homeFlag: FLAG("de"),
    awayCode: "CIV",
    awayName: "Côte d'Ivoire",
    awayFlag: FLAG("ci"),
    date: "2026-06-21",
    dateLabel: "Jun 21",
    time: "2:00 AM",
    group: "E",
    status: "upcoming",
  },
  {
    homeCode: "ECU",
    homeName: "Ecuador",
    homeFlag: FLAG("ec"),
    awayCode: "CUW",
    awayName: "Curaçao",
    awayFlag: FLAG("cw"),
    date: "2026-06-21",
    dateLabel: "Jun 21",
    time: "6:00 AM",
    group: "E",
    status: "upcoming",
  },
  {
    homeCode: "TUN",
    homeName: "Tunisia",
    homeFlag: FLAG("tn"),
    awayCode: "JPN",
    awayName: "Japan",
    awayFlag: FLAG("jp"),
    date: "2026-06-21",
    dateLabel: "Jun 21",
    time: "10:00 AM",
    group: "F",
    status: "upcoming",
  },
  {
    homeCode: "ESP",
    homeName: "Spain",
    homeFlag: FLAG("es"),
    awayCode: "KSA",
    awayName: "Saudi Arabia",
    awayFlag: FLAG("sa"),
    date: "2026-06-21",
    dateLabel: "Jun 21",
    time: "10:00 PM",
    group: "H",
    status: "upcoming",
  },
  // Jun 22
  {
    homeCode: "BEL",
    homeName: "Belgium",
    homeFlag: FLAG("be"),
    awayCode: "IRN",
    awayName: "Iran",
    awayFlag: FLAG("ir"),
    date: "2026-06-22",
    dateLabel: "Jun 22",
    time: "1:00 AM",
    group: "G",
    status: "upcoming",
  },
  {
    homeCode: "URU",
    homeName: "Uruguay",
    homeFlag: FLAG("uy"),
    awayCode: "CPV",
    awayName: "Cabo Verde",
    awayFlag: FLAG("cv"),
    date: "2026-06-22",
    dateLabel: "Jun 22",
    time: "4:00 AM",
    group: "H",
    status: "upcoming",
  },
  {
    homeCode: "NZL",
    homeName: "New Zealand",
    homeFlag: FLAG("nz"),
    awayCode: "EGY",
    awayName: "Egypt",
    awayFlag: FLAG("eg"),
    date: "2026-06-22",
    dateLabel: "Jun 22",
    time: "7:00 AM",
    group: "G",
    status: "upcoming",
  },
  {
    homeCode: "ARG",
    homeName: "Argentina",
    homeFlag: FLAG("ar"),
    awayCode: "AUT",
    awayName: "Austria",
    awayFlag: FLAG("at"),
    date: "2026-06-22",
    dateLabel: "Jun 22",
    time: "11:00 PM",
    group: "J",
    status: "upcoming",
  },
  // Jun 23
  {
    homeCode: "FRA",
    homeName: "France",
    homeFlag: FLAG("fr"),
    awayCode: "IRQ",
    awayName: "Iraq",
    awayFlag: FLAG("iq"),
    date: "2026-06-23",
    dateLabel: "Jun 23",
    time: "3:00 AM",
    group: "I",
    status: "upcoming",
  },
  {
    homeCode: "NOR",
    homeName: "Norway",
    homeFlag: FLAG("no"),
    awayCode: "SEN",
    awayName: "Senegal",
    awayFlag: FLAG("sn"),
    date: "2026-06-23",
    dateLabel: "Jun 23",
    time: "6:00 AM",
    group: "I",
    status: "upcoming",
  },
  {
    homeCode: "JOR",
    homeName: "Jordan",
    homeFlag: FLAG("jo"),
    awayCode: "ALG",
    awayName: "Algeria",
    awayFlag: FLAG("dz"),
    date: "2026-06-23",
    dateLabel: "Jun 23",
    time: "9:00 AM",
    group: "J",
    status: "upcoming",
  },
  {
    homeCode: "POR",
    homeName: "Portugal",
    homeFlag: FLAG("pt"),
    awayCode: "UZB",
    awayName: "Uzbekistan",
    awayFlag: FLAG("uz"),
    date: "2026-06-23",
    dateLabel: "Jun 23",
    time: "11:00 PM",
    group: "K",
    status: "upcoming",
  },
  // Jun 24
  {
    homeCode: "ENG",
    homeName: "England",
    homeFlag: FLAG("gb-eng"),
    awayCode: "GHA",
    awayName: "Ghana",
    awayFlag: FLAG("gh"),
    date: "2026-06-24",
    dateLabel: "Jun 24",
    time: "2:00 AM",
    group: "L",
    status: "upcoming",
  },
  {
    homeCode: "PAN",
    homeName: "Panama",
    homeFlag: FLAG("pa"),
    awayCode: "CRO",
    awayName: "Croatia",
    awayFlag: FLAG("hr"),
    date: "2026-06-24",
    dateLabel: "Jun 24",
    time: "5:00 AM",
    group: "L",
    status: "upcoming",
  },
  {
    homeCode: "COL",
    homeName: "Colombia",
    homeFlag: FLAG("co"),
    awayCode: "COD",
    awayName: "DR Congo",
    awayFlag: FLAG("cd"),
    date: "2026-06-24",
    dateLabel: "Jun 24",
    time: "8:00 AM",
    group: "K",
    status: "upcoming",
  },
  // Jun 25
  {
    homeCode: "SUI",
    homeName: "Switzerland",
    homeFlag: FLAG("ch"),
    awayCode: "CAN",
    awayName: "Canada",
    awayFlag: FLAG("ca"),
    date: "2026-06-25",
    dateLabel: "Jun 25",
    time: "1:00 AM",
    group: "B",
    status: "upcoming",
  },
  {
    homeCode: "BIH",
    homeName: "Bosnia",
    homeFlag: FLAG("ba"),
    awayCode: "QAT",
    awayName: "Qatar",
    awayFlag: FLAG("qa"),
    date: "2026-06-25",
    dateLabel: "Jun 25",
    time: "1:00 AM",
    group: "B",
    status: "upcoming",
  },
  {
    homeCode: "SCO",
    homeName: "Scotland",
    homeFlag: FLAG("gb-sct"),
    awayCode: "BRA",
    awayName: "Brazil",
    awayFlag: FLAG("br"),
    date: "2026-06-25",
    dateLabel: "Jun 25",
    time: "4:00 AM",
    group: "C",
    status: "upcoming",
  },
  {
    homeCode: "MAR",
    homeName: "Morocco",
    homeFlag: FLAG("ma"),
    awayCode: "HAI",
    awayName: "Haiti",
    awayFlag: FLAG("ht"),
    date: "2026-06-25",
    dateLabel: "Jun 25",
    time: "4:00 AM",
    group: "C",
    status: "upcoming",
  },
  {
    homeCode: "CZE",
    homeName: "Czechia",
    homeFlag: FLAG("cz"),
    awayCode: "MEX",
    awayName: "Mexico",
    awayFlag: FLAG("mx"),
    date: "2026-06-25",
    dateLabel: "Jun 25",
    time: "7:00 AM",
    group: "A",
    status: "upcoming",
  },
  {
    homeCode: "RSA",
    homeName: "South Africa",
    homeFlag: FLAG("za"),
    awayCode: "KOR",
    awayName: "Korea",
    awayFlag: FLAG("kr"),
    date: "2026-06-25",
    dateLabel: "Jun 25",
    time: "7:00 AM",
    group: "A",
    status: "upcoming",
  },
  // Jun 26
  {
    homeCode: "CUW",
    homeName: "Curaçao",
    homeFlag: FLAG("cw"),
    awayCode: "CIV",
    awayName: "Côte d'Ivoire",
    awayFlag: FLAG("ci"),
    date: "2026-06-26",
    dateLabel: "Jun 26",
    time: "2:00 AM",
    group: "E",
    status: "upcoming",
  },
  {
    homeCode: "ECU",
    homeName: "Ecuador",
    homeFlag: FLAG("ec"),
    awayCode: "GER",
    awayName: "Germany",
    awayFlag: FLAG("de"),
    date: "2026-06-26",
    dateLabel: "Jun 26",
    time: "2:00 AM",
    group: "E",
    status: "upcoming",
  },
  {
    homeCode: "JPN",
    homeName: "Japan",
    homeFlag: FLAG("jp"),
    awayCode: "SWE",
    awayName: "Sweden",
    awayFlag: FLAG("se"),
    date: "2026-06-26",
    dateLabel: "Jun 26",
    time: "5:00 AM",
    group: "F",
    status: "upcoming",
  },
  {
    homeCode: "TUN",
    homeName: "Tunisia",
    homeFlag: FLAG("tn"),
    awayCode: "NED",
    awayName: "Netherlands",
    awayFlag: FLAG("nl"),
    date: "2026-06-26",
    dateLabel: "Jun 26",
    time: "5:00 AM",
    group: "F",
    status: "upcoming",
  },
  {
    homeCode: "TUR",
    homeName: "Turkey",
    homeFlag: FLAG("tr"),
    awayCode: "USA",
    awayName: "USA",
    awayFlag: FLAG("us"),
    date: "2026-06-26",
    dateLabel: "Jun 26",
    time: "8:00 AM",
    group: "D",
    status: "upcoming",
  },
  {
    homeCode: "PAR",
    homeName: "Paraguay",
    homeFlag: FLAG("py"),
    awayCode: "AUS",
    awayName: "Australia",
    awayFlag: FLAG("au"),
    date: "2026-06-26",
    dateLabel: "Jun 26",
    time: "8:00 AM",
    group: "D",
    status: "upcoming",
  },
  // Jun 27
  {
    homeCode: "NOR",
    homeName: "Norway",
    homeFlag: FLAG("no"),
    awayCode: "FRA",
    awayName: "France",
    awayFlag: FLAG("fr"),
    date: "2026-06-27",
    dateLabel: "Jun 27",
    time: "1:00 AM",
    group: "I",
    status: "upcoming",
  },
  {
    homeCode: "SEN",
    homeName: "Senegal",
    homeFlag: FLAG("sn"),
    awayCode: "IRQ",
    awayName: "Iraq",
    awayFlag: FLAG("iq"),
    date: "2026-06-27",
    dateLabel: "Jun 27",
    time: "1:00 AM",
    group: "I",
    status: "upcoming",
  },
  {
    homeCode: "URU",
    homeName: "Uruguay",
    homeFlag: FLAG("uy"),
    awayCode: "ESP",
    awayName: "Spain",
    awayFlag: FLAG("es"),
    date: "2026-06-27",
    dateLabel: "Jun 27",
    time: "6:00 AM",
    group: "H",
    status: "upcoming",
  },
  {
    homeCode: "CPV",
    homeName: "Cabo Verde",
    homeFlag: FLAG("cv"),
    awayCode: "KSA",
    awayName: "Saudi Arabia",
    awayFlag: FLAG("sa"),
    date: "2026-06-27",
    dateLabel: "Jun 27",
    time: "6:00 AM",
    group: "H",
    status: "upcoming",
  },
  {
    homeCode: "NZL",
    homeName: "New Zealand",
    homeFlag: FLAG("nz"),
    awayCode: "BEL",
    awayName: "Belgium",
    awayFlag: FLAG("be"),
    date: "2026-06-27",
    dateLabel: "Jun 27",
    time: "9:00 AM",
    group: "G",
    status: "upcoming",
  },
  {
    homeCode: "EGY",
    homeName: "Egypt",
    homeFlag: FLAG("eg"),
    awayCode: "IRN",
    awayName: "Iran",
    awayFlag: FLAG("ir"),
    date: "2026-06-27",
    dateLabel: "Jun 27",
    time: "9:00 AM",
    group: "G",
    status: "upcoming",
  },
  // Jun 28
  {
    homeCode: "PAN",
    homeName: "Panama",
    homeFlag: FLAG("pa"),
    awayCode: "ENG",
    awayName: "England",
    awayFlag: FLAG("gb-eng"),
    date: "2026-06-28",
    dateLabel: "Jun 28",
    time: "3:00 AM",
    group: "L",
    status: "upcoming",
  },
  {
    homeCode: "CRO",
    homeName: "Croatia",
    homeFlag: FLAG("hr"),
    awayCode: "GHA",
    awayName: "Ghana",
    awayFlag: FLAG("gh"),
    date: "2026-06-28",
    dateLabel: "Jun 28",
    time: "3:00 AM",
    group: "L",
    status: "upcoming",
  },
  {
    homeCode: "COL",
    homeName: "Colombia",
    homeFlag: FLAG("co"),
    awayCode: "POR",
    awayName: "Portugal",
    awayFlag: FLAG("pt"),
    date: "2026-06-28",
    dateLabel: "Jun 28",
    time: "5:30 AM",
    group: "K",
    status: "upcoming",
  },
  {
    homeCode: "COD",
    homeName: "DR Congo",
    homeFlag: FLAG("cd"),
    awayCode: "UZB",
    awayName: "Uzbekistan",
    awayFlag: FLAG("uz"),
    date: "2026-06-28",
    dateLabel: "Jun 28",
    time: "5:30 AM",
    group: "K",
    status: "upcoming",
  },
  {
    homeCode: "JOR",
    homeName: "Jordan",
    homeFlag: FLAG("jo"),
    awayCode: "ARG",
    awayName: "Argentina",
    awayFlag: FLAG("ar"),
    date: "2026-06-28",
    dateLabel: "Jun 28",
    time: "8:00 AM",
    group: "J",
    status: "upcoming",
  },
  {
    homeCode: "ALG",
    homeName: "Algeria",
    homeFlag: FLAG("dz"),
    awayCode: "AUT",
    awayName: "Austria",
    awayFlag: FLAG("at"),
    date: "2026-06-28",
    dateLabel: "Jun 28",
    time: "8:00 AM",
    group: "J",
    status: "upcoming",
  },
];
